# Generated by Django 4.2.3 on 2023-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('model_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
