# Generated by Django 4.0.7 on 2023-07-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
