# Generated by Django 4.2.3 on 2023-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.CharField(default='media/images/blue.jpg', max_length=40),
        ),
    ]
